name: Auto Update README

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: chmod +x scripts/update_readme.sh

      - run: bash scripts/update_readme.sh

      - run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "auto update" || echo "no change"
          git push
